### ISSUE TITLE
Soundflower 1.6.6b crashes after updating to OS X Yosemite

### ISSUE THREAD

**Issue by stefanborghys** [RogueAmoeba/Soundflower#20]
I updated my mac to OS X Yosemite.
Afterwards when starting Soundflower i noticed the in-active icon kept showing up 
when moving over the icon.
Looking in the Activity Monitor i noticed the process was marked as not responding and had to kill it.

I decided to remove and reinstall the latest version (Soundflower-1.6.6b.dmg).
After restarting i got the same result as above.

I noticed other people having trouble when running it on the latest Mac OS X.
Maybe it's related to https://github.com/RogueAmoeba/Soundflower/issues/19
But at least they get it running.
Any suggestions or other ways i can help?

**Comment by rogerwilco1974** [comment]
I'd just like to say that I installed @mattingalls build, whilst not uninstalling the previous build that crashed, and the soundflowerapp now seems to work when using the 64channel device, not the 2channel device.

So, thanks, I think!

**Comment by ghost** [comment]
@mattingalls. Tried to download and install your build but it didn't work. Soundflower devices were still loaded in System Preferences:Sound. Opened up terminal and ran:
sudo kextunload /System/Library/Extensions/Soundflower.kext
sudo rm /System/Library/Extensions/Soundflower.kext
Tells me to enter my password, so I do. Tells me "Sorry try again" even though I know I've entered the right password. Enter same password again, and receive the message "Can't open CFBundle for /System/Library/Extensions/Soundflower.kext.
Can't create /System/Library/Extensions/Soundflower.kext.
Andrews-MacBook-Pro:~ andrewmarkos$"
Then tried downloading "Soundflower.kext.zip" file. Does not automatically unzip in my downloads folder so I open it. Open terminal and type "sudo mv ~/Downloads/Soundflower.kext /Library/Extensions
sudo chown -R root:wheel /Library/Extensions/Soundflower.kext
sudo kextload /Library/Extensions/Soundflower.kext". Nothing happens

**Comment by mattingalls** [comment]
@Zinedine-Socrates the rm errors might be because old version isn't there.  what do you mean by "nothing happens"? in general if no error is printed after terminal commands, it means it WORKED

**Comment by stefanborghys** [comment]
I'll close this issue since it's over 8 years old.
