### ISSUE TITLE
Installing 1.6.7 Yosemite 10.10.3 fail

### ISSUE THREAD

**Issue by lesyk** [RogueAmoeba/Soundflower#31]
I've build it in deploy mode after installation fails, imgs:

![screen shot 2015-02-23 at 14 04 20](https://cloud.githubusercontent.com/assets/818588/6328188/136d193c-bb65-11e4-88e4-ff0b34553d01.png)
![screen shot 2015-02-23 at 14 04 26](https://cloud.githubusercontent.com/assets/818588/6328187/134d1628-bb65-11e4-8ff7-82e22eeec311.png)
![screen shot 2015-02-23 at 14 04 03](https://cloud.githubusercontent.com/assets/818588/6328189/136fcaba-bb65-11e4-9d8d-ea811e6f3b6b.png)

**Comment by ghost** [comment]
Same here.

**Comment by emabartolomucci** [comment]
Same for me.

**Comment by chrisphenry** [comment]
I'm on 10.10.2 and third this, not seeing anything immediately relatable in console logs.
Built and installed both dev and dep versions to the same effect.
Checked kext perms - all ok.

![tools_ _bash_ _89x24](https://cloud.githubusercontent.com/assets/868072/6794965/429b2ec4-d1d1-11e4-84d6-5f33c5ae7fe8.png)

**Comment by chrisphenry** [comment]
Seems the code signing is the issue as indicated by kextutil:

```
Diagnostics for /System/Library/Extensions/Soundflower.kext:
Code Signing Failure: not code signed
ERROR: invalid signature for com.Cycling74.driver.Soundflower, will not load
```

One solution, at least temporarily until the code signing is fixed would be to disable kext signing in OS X as follows: (**WARNING:** know the risks of doing this before doing so, no warranty implied)...

```
sudo nvram boot-args=kext-dev-mode=1
```

Then restart your mac for these changes to take effect:

```
sudo shutdown -r now
```

Soundflowerbed should now work as expected.

**Comment by ldexterldesign** [comment]
+1

I'll wait for the fix

Thanks

**Comment by kybernetyk** [comment]
2.0.2b from https://github.com/mattingalls/Soundflower/releases works for me

**Comment by ldexterldesign** [comment]
@kybernetyk hey, and a helpful DMG installer too! Kind thanks.
