### ISSUE TITLE
Stopped working on macOS 10.13.5

### ISSUE THREAD

**Issue by Ker-jo** [RogueAmoeba/Soundflower#82]
Hi, I've been using this kext for a long time. Thanks to the devs.
I stopped using it for about 1 month and now it doesn't work anymore. The inputs and outputs "Soundflower (2ch)" and "Soundflower (64ch)" still appear in the I/O lists.

I tried different setups like playing music to soundflower and recording it with QuickTime Player. Soundflower's output doesn't produce any sound. QuickTime recorded nothing.

I recently updated Xcode and macOS which might have caused the issue. (9.4.1 and 10.13.5)
I also tried to reinstall it from https://github.com/mattingalls/Soundflower/releases/tag/2.0b2.

Here is a test I made using Audio Hijack Pro.
<img width="446" alt="screen shot" src="https://user-images.githubusercontent.com/40443688/41688166-49f89650-74eb-11e8-96ed-9132d5eae64a.png">

Hopefully, there are still people on this old repo and can help me.

**Comment by mattingalls** [comment]
first thing to do is open Audio MIDI Setup and check that all volume sliders are up and all mute buttons are off -- some apps can turn Soundflower off without you knowing.

**Comment by Ker-jo** [comment]
You were right, the master was muted. Thank you !
